### ISSUE TITLE
Add encoding declare in setup.py

### ISSUE THREAD

**Issue by khapota** [raymontag/keepassc#69]
Hi,
When i run install script:
<code>
sudo python setup.py install
 File "setup.py", line 25
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
</code>
I think it is because your name :D and we should add:
<code># -*- coding: utf-8 -*-</code>

**Comment by raymontag** [comment]
Yep, this is because of my name :P But you solve it by using Python 3 as KeePassC is not supposed to work with Python 2. It's not even possible to open a database with Python 2 in KeePassC due to some functions added in Python 3.3 I use.

**Comment by khapota** [comment]
Ok, i will run with python3 command :D. In Ubuntu, default is still python 2.

**Comment by raymontag** [comment]
You propably want to set the Shebang to #!/usr/bin/python3 instead of just python in bin/keepassc.

**Comment by khapota** [comment]
Thanks :dancer:

**Comment by sebma** [comment]
I have the same problem as my Ubuntu defaults to python2.

Why not add the following Shebang in the first line of `setup.py`:
`#!/usr/bin/env python3`
add the execution rights to it and run this command for installation:
`sudo ./setup.py install`

So that nobody will see this `SyntaxError: Non-ASCII character  '\xc3' in file setup.py` ever again :)
